import test from 'node:test';import assert from 'node:assert/strict';
import {JSDOM} from 'jsdom';import createDOMPurify from 'dompurify';
import {normalizeDocument,documentHTML,printHTML,pageSettings} from '../public/contratoDocumento.js';
import {readDocument} from '../public/contratosEditor.js';
test('Editor escapes text and rejects active or arbitrary HTML nodes',()=>{assert.equal(documentHTML(['<script>alert(1)</script>']),'&lt;script&gt;alert(1)&lt;/script&gt;');for(const tag of ['script','img','iframe','style','svg'])assert.throws(()=>normalizeDocument([{tag,children:[]}]))});
test('Editor drops pasted scripts, images, links, handlers and unapproved styles',()=>{const d=new JSDOM('<div id="x"><p onclick="alert(1)" style="text-align:center;color:red">Texto</p><script>x</script><img src=x><a href="javascript:x">Link</a></div>').window.document;const html=documentHTML(readDocument(d.querySelector('#x')));assert.equal(html,'<p style="text-align:center">Texto</p><div>Link</div>');});
test('Print uses selected paper, preserves tables and marks unissued drafts',()=>{const html=printHTML([{tag:'table',children:[{tag:'tr',children:[{tag:'td',children:['Cuota 1']}]}]}],{size:'Legal',orientation:'landscape'},'<title>',{draft:true});assert.match(html,/size:Legal landscape/);assert.match(html,/BORRADOR/);assert.match(html,/&lt;title&gt;/);assert.match(html,/<td>Cuota 1/);assert.throws(()=>pageSettings({size:'A4;url(x)',orientation:'portrait'}));});
test('Complex and oversized documents rejected before storage',()=>{assert.throws(()=>normalizeDocument(['x'.repeat(70001)]));let n='x';for(let i=0;i<32;i++)n={tag:'div',children:[n]};assert.throws(()=>normalizeDocument([n]));});
test('Editor saves models and immutable document versions using only contract endpoints',async()=>{
 const {contractsEditor}=await import('../public/contratosEditor.js');const dom=new JSDOM('<main><div id="view"></div></main>',{url:'https://qa.invalid/'});const w=dom.window;const previous={window:globalThis.window,document:globalThis.document,MutationObserver:globalThis.MutationObserver,confirm:globalThis.confirm};Object.assign(globalThis,{window:w,document:w.document,MutationObserver:w.MutationObserver,confirm:()=>true});
 const calls=[];let stored;const api=async(url,options)=>{calls.push(url);if(url.startsWith('/clientes'))return [{id:'client',nombre:'QA'}];if(url.includes('/fuentes'))return {cliente:{id:'client',nombre:'QA'},creditos:[]};if(options){const b=JSON.parse(options.body);if(url.endsWith('/modelos'))return {...b,id:'model',nombre:b.nombre,version:1};stored={...b,id:'doc',revision:1,versiones:[{...b,revision:1}]};return stored;}return {modelos:[],contratos:[]};};
 try{const view=w.document.querySelector('#view');await contractsEditor(view,{api,setHTML:(el,s)=>{el.innerHTML=createDOMPurify(w).sanitize(s,{USE_PROFILES:{html:true,svg:true},FORBID_TAGS:['style'],FORBID_ATTR:['srcdoc']});},negocios:[],negocioActual:'store',toast:m=>{throw Error(m);}});view.querySelector('#docNew').click();await new Promise(r=>setTimeout(r,0));const paper=view.querySelector('#docPaper');assert.ok(paper);assert.equal(paper.contentEditable,'true');paper.textContent='QA contrato';view.querySelector('#docClient').value='client';await view.querySelector('#docClient').onchange();await view.querySelector('#docSave').onclick();assert.equal(stored.documento[0],'QA contrato');assert.equal(stored.estado,'borrador');assert.match(view.querySelector('#docVersions').textContent,/v1/);assert.ok(calls.every(x=>x.startsWith('/contratos')||x.startsWith('/clientes')));}
 finally{w.close();Object.assign(globalThis,previous);}
});
