import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {JSDOM} from 'jsdom';
import * as acorn from 'acorn';
const source=fs.readFileSync(new URL('../public/app.js',import.meta.url),'utf8');
const page=fs.readFileSync(new URL('../public/index.html',import.meta.url),'utf8');
const purifier=fs.readFileSync(new URL('../public/vendor/purify.min.js',import.meta.url),'utf8');
function browser(respond=()=>[]){
 const dom=new JSDOM(page,{url:'https://zilky.test/',runScripts:'outside-only',pretendToBeVisual:true});
 const calls=[];dom.window.fetch=async(url,opts={})=>{calls.push({url,opts});return {ok:true,status:200,json:async()=>respond(url,opts)};};
 dom.window.confirm=()=>true;dom.window.eval(purifier);dom.window.eval(source+'\nwindow.auditState=state;');
 return {dom,w:dom.window,calls};
}
test('Cobrar sin negocio genera URL válida con signo de pregunta',async()=>{const b=browser(url=>url.includes('cobranza')?{hoy:[],proximas:[],vencidas:[],todas:[]}:[]);try{await b.w.viewCobrar(b.w.document.getElementById('view'));assert.equal(b.calls[0].url,'/api/dashboard/cobranza?ventana_dias=7');}finally{b.w.close();}});
test('Con deuda solicita filtro real al backend y conserva negocio',async()=>{const b=browser();try{b.w.auditState.clientesTab='deuda';b.w.auditState.negocioActual='negocio-B';const list=b.w.document.createElement('div');list.id='clientesList';b.w.document.body.append(list);await b.w.renderClientesList('Perez');const url=new URL(b.calls[0].url,'https://zilky.test');assert.equal(url.searchParams.get('con_deuda'),'1');assert.equal(url.searchParams.get('negocio_id'),'negocio-B');assert.equal(url.searchParams.get('q'),'Perez');}finally{b.w.close();}});
test('Clientes con nombre malicioso se muestran como texto, no como HTML',async()=>{const payload='<img src=x onerror="window.pwned=1"><button data-action="logout">X</button>';const b=browser(()=>[{id:'id',nombre:payload,apellido:'Test'}]);try{const list=b.w.document.createElement('div');list.id='clientesList';b.w.document.body.append(list);await b.w.renderClientesList('');assert.ok(list.textContent.includes(payload));assert.equal(list.querySelector('img'),null);assert.equal(list.querySelector('button'),null);assert.equal(b.w.pwned,undefined);}finally{b.w.close();}});
test('Sanitizador quita eventos, scripts y enlaces javascript',()=>{const b=browser();try{const el=b.w.document.getElementById('view');b.w.setHTML(el,'<img src=x onerror="alert(1)"><script>alert(1)</script><a href="javascript:alert(1)">X</a><svg onload="alert(1)"></svg>');assert.equal(el.querySelector('script'),null);assert.equal(el.querySelector('[onerror],[onload],[href^="javascript:"]'),null);}finally{b.w.close();}});
test('Las hojas conservan markup de UI y siguen sanitizando datos',()=>{const b=browser();try{b.w.openSheet('<button id="sheetAction">Guardar</button><img src=x onerror="alert(1)">');assert.equal(b.w.document.getElementById('sheetAction').textContent,'Guardar');assert.equal(b.w.document.querySelector('#activeSheet img')?.getAttribute('onerror'),null);}finally{b.w.close();}});
test('El calendario conserva sus celdas renderizadas',async()=>{const b=browser(url=>url.includes('/dashboard/calendario?')?[{fecha:'2026-10-02',cantidad:1,montoCentavos:1000}]:[]);try{b.w.auditState.negocioActual='n';b.w.auditState.negocios=[{id:'n',nombre:'Negocio'}];b.w.auditState.calMes='2026-10';await b.w.viewCalendario(b.w.document.getElementById('view'));assert.ok(b.w.document.querySelector('.cal-grid .cal-day'));assert.ok(b.w.document.querySelector('[data-action="ver-dia-calendario"]'));}finally{b.w.close();}});
test('Toda escritura innerHTML pasa por el único sanitizador',()=>{const ast=acorn.parse(source,{ecmaVersion:'latest'});let helper;const sinks=[];function walk(n){if(!n||typeof n!=='object')return;if(n.type==='FunctionDeclaration'&&n.id.name==='setHTML')helper=n;if(n.type==='AssignmentExpression'&&n.left?.property?.name==='innerHTML')sinks.push(n);for(const v of Object.values(n)){if(Array.isArray(v))v.forEach(walk);else if(v&&typeof v==='object')walk(v);}}walk(ast);assert.equal(sinks.length,1);assert.ok(sinks[0].start>helper.start&&sinks[0].end<helper.end);assert.ok(!/onclick\s*=\s*["']/.test(source));});
test('Acción de empleados sigue funcionando sin onclick inline',async()=>{const b=browser(url=>url==='/api/usuarios'?[{id:'u1',rol:'empleado',nombre:'Ana',email:'a@b.test',activo:1,negocios:[]}]:[]);try{await b.w.viewEmpleados(b.w.document.getElementById('view'));const button=b.w.document.querySelector('[data-action="toggle-empleado"]');assert.ok(button);button.click();await new Promise(r=>setTimeout(r,10));const call=b.calls.find(x=>x.url==='/api/usuarios/u1'&&x.opts.method==='PATCH');assert.deepEqual(JSON.parse(call.opts.body),{activo:0});}finally{b.w.close();}});
test('Ficha sin permiso financiero no rompe el frontend ni muestra importes',async()=>{const b=browser(()=>({id:'c',nombre:'Cliente',apellido:'Uno',historial:null,creditos:[],pagos:[]}));try{await b.w.viewClienteDetail(b.w.document.getElementById('view'),'c');assert.match(b.w.document.getElementById('view').textContent,/No tenés permiso/);}finally{b.w.close();}});
test('Entrega inicial identificada y sin botón de anulación; pago normal sí',async()=>{const b=browser(()=>[{id:'entrega',numero:'E1',tipo_pago:'entrega_inicial',estado:'emitido',monto_centavos:3000,fecha_hora:'2026-10-02T12:00:00-03:00'},{id:'cuota',numero:'C1',tipo_pago:'cuota',estado:'emitido',monto_centavos:1000,fecha_hora:'2026-10-02T12:00:00-03:00'}]);try{b.w.auditState.negocioActual='n';b.w.auditState.usuario={rol:'administrador'};await b.w.viewComprobantes(b.w.document.getElementById('view'));assert.match(b.w.document.getElementById('view').textContent,/Entrega inicial/);assert.equal(b.w.document.querySelector('[data-action="anular-comprobante"][data-id="entrega"]'),null);assert.ok(b.w.document.querySelector('[data-action="anular-comprobante"][data-id="cuota"]'));}finally{b.w.close();}});
test('Pantalla de invitación conserva creación de contraseña sin handlers inline',async()=>{const b=browser(url=>url.includes('consultar')?{email:'a@b.test',negocios:[],expira_en:'2099-01-01'}:url.includes('aceptar')?{token:'session'}:url.endsWith('/auth/yo')?{rol:'administrador',negocios:[]}:[]);try{b.w.history.replaceState({},'','/?token=invite');await b.w.renderAceptarInvitacion();b.w.document.getElementById('invPassword').value='password-test';b.w.document.getElementById('invPassword2').value='password-test';await b.w.document.getElementById('btnAceptarInvitacion').onclick();const call=b.calls.find(x=>x.url==='/api/auth/invitacion/aceptar');assert.equal(JSON.parse(call.opts.body).token,'invite');assert.equal(b.w.localStorage.getItem('zilky_token'),'session');}finally{b.w.close();}});
