import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import { JSDOM } from 'jsdom';
const source=fs.readFileSync(new URL('../public/app.js',import.meta.url),'utf8');
const page=fs.readFileSync(new URL('../public/index.html',import.meta.url),'utf8');
const purifier=fs.readFileSync(new URL('../public/vendor/purify.min.js',import.meta.url),'utf8');
const negocios=[{id:'a',nombre:'Apple'},{id:'b',nombre:'Indumentaria'},{id:'c',nombre:'Reparaciones'}];
const inv=(estado)=>({id:estado,email:estado+'@test.invalid',estado,expira_en:'2099-01-01',negocios:[{negocio_id:'a',permisos:{'clientes.ver':true}}]});
const empleados=[{id:'u',nombre:'Lucas',email:'lucas@test.invalid',rol:'empleado',activo:1,negocios:[{negocio_id:'a',permisos:{'pagos.registrar':true},activo:1},{negocio_id:'b',permisos:{'pagos.registrar':false,'clientes.ver':true},activo:1}]},{id:'inactivo',nombre:'Ana',email:'ana@test.invalid',rol:'empleado',activo:0,negocios:[]},{id:'admin',rol:'administrador'}];
function browser(respond=(url)=>url==='/api/usuarios'?empleados:url==='/api/invitaciones'?['pendiente','usada','vencida','revocada'].map(inv):url==='/api/negocios'?negocios:[]) {
 const dom=new JSDOM(page,{url:'https://zilky.test/',runScripts:'outside-only',pretendToBeVisual:true});const w=dom.window,calls=[];
 w.fetch=async(url,opts={})=>{calls.push({url,opts});const result=await respond(url,opts);return {ok:!result?.error,status:result?.error?410:200,json:async()=>result};};w.confirm=()=>true;w.eval(purifier);w.eval(source+'\nwindow.testState=state;');w.testState.usuario={rol:'administrador'};
 return {w,calls,view:w.document.getElementById('view')};
}
const plain=x=>JSON.parse(JSON.stringify(x));
test('Etapa2 UI: empleados activos e inactivos, negocios y permisos por negocio visibles',async()=>{const b=browser();try{await b.w.viewEmpleados(b.view);assert.match(b.view.textContent,/Lucas · Activo/);assert.match(b.view.textContent,/Ana · Inactivo/);assert.match(b.view.textContent,/Apple/);assert.match(b.view.textContent,/Indumentaria/);const rows=b.view.querySelectorAll('.list-item');assert.match(rows[0].querySelectorAll('details')[0].textContent,/pagos.registrar/);assert.ok(!rows[0].querySelectorAll('details')[1].textContent.includes('pagos.registrar'));assert.equal(b.view.querySelector('[data-id="admin"]'),null);}finally{b.w.close();}});
test('Etapa2 UI: los cuatro estados muestran únicamente acciones válidas',async()=>{const b=browser();try{await b.w.viewEmpleados(b.view);for(const state of ['pendiente','usada','vencida','revocada']){const el=b.view.querySelector(`[data-invitacion-estado="${state}"]`);assert.ok(el);assert.equal(!!el.querySelector('[data-action="revocar-invitacion"]'),state==='pendiente');assert.equal(!!el.querySelector('[data-action="regenerar-invitacion"]'),state!=='usada');}}finally{b.w.close();}});
test('Etapa2 UI: seleccionar varios negocios conserva permisos diferentes y desactivar negocio deshabilita sus casillas',async()=>{const b=browser();try{await b.w.viewEmpleados(b.view);for(const id of ['a','b'])b.view.querySelector(`.inv-negocio-check[data-id="${id}"]`).click();b.view.querySelector('[data-negocio="a"][data-permiso="pagos.registrar"]').click();b.view.querySelector('[data-negocio="b"][data-permiso="clientes.ver"]').click();const a=plain(b.w.recogerAsignaciones('inv'));assert.equal(a.length,2);assert.equal(a[0].permisos['pagos.registrar'],true);assert.equal(a[1].permisos['pagos.registrar'],false);assert.equal(a[1].permisos['clientes.ver'],true);assert.ok(b.view.querySelector('[data-permiso="empleados.gestionar"]'));b.view.querySelector('.inv-negocio-check[data-id="b"]').click();assert.equal(b.w.recogerAsignaciones('inv').length,1);assert.equal(b.view.querySelector('[data-negocio="b"][data-permiso="clientes.ver"]').disabled,true);}finally{b.w.close();}});
test('Etapa2 UI: invitar envía selección por negocio y ofrece enlace si no hay email',async()=>{const b=browser((url,opts)=>url==='/api/invitaciones'&&opts.method==='POST'?{token:'test-only',emailEnviado:false,emailError:'Email no configurado'}:url==='/api/negocios'?negocios:[]);try{await b.w.viewEmpleados(b.view);b.w.document.getElementById('invEmail').value='nuevo@test.invalid';b.view.querySelector('.inv-negocio-check').click();await b.w.enviarInvitacion();const call=b.calls.find(x=>x.opts.method==='POST');assert.equal(JSON.parse(call.opts.body).negocios.length,1);assert.match(b.w.document.getElementById('activeSheet').textContent,/Email no configurado/);assert.match(b.w.document.getElementById('invLinkResultado').value,/\?token=test-only/);}finally{b.w.close();}});
test('Etapa2 UI: no manda invitaciones sin negocio ni con email inválido',async()=>{const b=browser();try{await b.w.viewEmpleados(b.view);b.w.document.getElementById('invEmail').value='incorrecto';await b.w.enviarInvitacion();b.w.document.getElementById('invEmail').value='a@b.test';await b.w.enviarInvitacion();assert.ok(!b.calls.some(x=>x.opts.method==='POST'));}finally{b.w.close();}});
test('Etapa2 UI: editor precarga asignaciones actuales y envía cambios atómicos en un PATCH',async()=>{const b=browser(url=>url==='/api/usuarios/u'?empleados[0]:url==='/api/negocios'?negocios:[]);try{await b.w.editarEmpleado('u');assert.equal(b.w.document.querySelector('.edit-negocio-check[data-id="a"]').checked,true);assert.equal(b.w.document.querySelector('[data-negocio="a"][data-permiso="pagos.registrar"]').checked,true);assert.equal(b.w.document.querySelector('[data-negocio="b"][data-permiso="pagos.registrar"]').checked,false);b.w.document.querySelector('.edit-negocio-check[data-id="a"]').click();await b.w.guardarEmpleado('u');const calls=b.calls.filter(x=>x.opts.method==='PATCH');assert.equal(calls.length,1);const data=JSON.parse(calls[0].opts.body);assert.equal(data.nombre,'Lucas');assert.equal(data.negocios.length,1);assert.equal(data.negocios[0].negocio_id,'b');}finally{b.w.close();}});
test('Etapa2 UI: manager ve gestión sin endpoints o formulario de invitaciones admin',async()=>{const b=browser();try{b.w.testState.usuario={rol:'empleado',negocios:[{negocio_id:'a',activo:1,permisos:{'empleados.gestionar':true}}]};await b.w.viewEmpleados(b.view);assert.ok(!b.calls.some(x=>x.url==='/api/invitaciones'));assert.equal(b.w.document.getElementById('invEmail'),null);await b.w.viewMas(b.view);assert.equal(b.view.querySelector('a[href="#/empleados"]').hidden,false);}finally{b.w.close();}});
test('Etapa2 UI: datos maliciosos de empleados e invitaciones permanecen texto',async()=>{const bad='<img src=x onerror="window.pwn=1">';const b=browser(url=>url==='/api/usuarios'?[{...empleados[0],nombre:bad}]:url==='/api/invitaciones'?[{...inv('pendiente'),email:bad}]:negocios);try{await b.w.viewEmpleados(b.view);assert.ok(b.view.textContent.includes(bad));assert.equal(b.view.querySelector('img'),null);assert.equal(b.w.pwn,undefined);}finally{b.w.close();}});
for(const mensaje of ['Invitación vencida','Invitación revocada','Invitación ya utilizada','Invitación no válida'])test('Etapa2 UI: '+mensaje+' bloquea formulario y no crea cuenta',async()=>{const b=browser(()=>({error:mensaje}));try{b.w.history.replaceState({},'','/?token=bad');await b.w.renderAceptarInvitacion();assert.equal(b.w.document.getElementById('invitacionInfo').textContent,mensaje);assert.equal(b.w.document.getElementById('btnAceptarInvitacion').disabled,true);assert.equal(b.w.document.getElementById('invPassword').disabled,true);assert.ok(!b.calls.some(x=>x.url.includes('/aceptar')));}finally{b.w.close();}});
test('Etapa2 UI: invitado ve email y negocios; contraseña distinta no se envía',async()=>{const b=browser(()=>({email:'lucas@test.invalid',nombre:'Lucas',expira_en:'2099-01-01',negocios}));try{b.w.history.replaceState({},'','/?token=valid');await b.w.renderAceptarInvitacion();assert.match(b.w.document.getElementById('invitacionInfo').textContent,/lucas@test.invalid/);assert.match(b.w.document.getElementById('invitacionInfo').textContent,/Reparaciones/);assert.equal(b.w.document.getElementById('invNombre').value,'Lucas');b.w.document.getElementById('invPassword').value='password-test';b.w.document.getElementById('invPassword2').value='diferente';await b.w.document.getElementById('btnAceptarInvitacion').onclick();assert.match(b.w.document.getElementById('invError').textContent,/no coinciden/);assert.ok(!b.calls.some(x=>x.url.includes('/aceptar')));}finally{b.w.close();}});
test('Etapa2 UI: no duplica solicitud de aceptación mientras espera respuesta',async()=>{let finish;const b=browser(url=>url.includes('/aceptar')?new Promise(resolve=>{finish=resolve;}):{email:'a@b.test',negocios:[],expira_en:'2099-01-01'});try{b.w.history.replaceState({},'','/?token=valid');await b.w.renderAceptarInvitacion();b.w.document.getElementById('invPassword').value='password-test';b.w.document.getElementById('invPassword2').value='password-test';const btn=b.w.document.getElementById('btnAceptarInvitacion');const pending=btn.onclick();await btn.onclick();assert.equal(b.calls.filter(x=>x.url.includes('/aceptar')).length,1);finish({error:'Invitación ya utilizada'});await pending;assert.match(b.w.document.getElementById('invError').textContent,/utilizada/);}finally{b.w.close();}});

test('Etapa2 UI: cerrar un modal anterior no elimina el nuevo resultado de invitación',async()=>{const b=browser();try{b.w.openSheet('<p>Anterior</p>');b.w.closeSheet();b.w.mostrarResultadoInvitacion({token:'nuevo',emailEnviado:false,emailError:'Sin envío'});await new Promise(r=>setTimeout(r,240));assert.ok(b.w.document.getElementById('invLinkResultado'));}finally{b.w.close();}});
