import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {JSDOM} from 'jsdom';
const source=fs.readFileSync(new URL('../public/app.js',import.meta.url),'utf8');
const page=fs.readFileSync(new URL('../public/index.html',import.meta.url),'utf8');
const purifier=fs.readFileSync(new URL('../public/vendor/purify.min.js',import.meta.url),'utf8');
const tick=()=>new Promise(r=>setImmediate(r));
const ficha={gestionCobranza:[{negocio_id:'qa',modo:'revisar'}],creditos:[{negocio_id:'qa',cuotas:[{id:'q1',numero:1,fecha_vencimiento:'2026-10-01',saldo_pendiente_centavos:10000}]}],contactosCobranza:[]};
function browser(respond=()=>ficha){const d=new JSDOM(page,{url:'https://zilky.test/',runScripts:'outside-only',pretendToBeVisual:true}),w=d.window,calls=[];
  w.fetch=async(url,opts={})=>{calls.push({url,opts});const b=await respond(url,opts);return {ok:true,json:async()=>b};};w.eval(purifier);w.eval(source+'\nwindow.qaState=state;');w.qaState.usuario={rol:'administrador'};w.qaState.negocioActual='qa';return {w,calls,el:id=>w.document.getElementById(id)};}
test('Etapa4 UI: muestra contacto separado del vencimiento y declara que no hay envíos automáticos',async()=>{const b=browser();try{await b.w.abrirContactosCobranza('c','qa');assert.match(b.el('activeSheet').textContent,/no cambia la fecha de vencimiento/);assert.match(b.el('activeSheet').textContent,/No se envían mensajes automáticamente/);assert.equal(b.el('contactoModo').value,'revisar');assert.match(b.el('contactoDestino').textContent,/01\/10\/2026/);}finally{b.w.close();}});
test('Etapa4 UI: doble clic solo programa una solicitud y reintento de red conserva UUID/cuerpo',async()=>{let fail=true;const b=browser((url,opts)=>{if(opts.method){if(fail)throw new Error('Red interrumpida');return {};}return ficha;});try{await b.w.abrirContactosCobranza('c','qa');b.el('contactoNota').value='QA';b.el('guardarContacto').click();b.el('guardarContacto').click();await tick();assert.equal(b.calls.filter(c=>c.opts.method).length,1);const original=b.calls.at(-1);b.el('contactoNota').value='No sustituir reintento';fail=false;b.el('guardarContacto').click();await tick();const nuevo=b.calls.findLast(c=>c.opts.method);assert.equal(nuevo.opts.body,original.opts.body);assert.equal(nuevo.url,original.url);}finally{b.w.close();}});
test('Etapa4 UI: no carga ni permite gestionar contactos sin permisos',async()=>{const b=browser();try{b.w.qaState.usuario={rol:'empleado'};await b.w.abrirContactosCobranza('c','qa');assert.equal(b.calls.length,0);assert.equal(b.el('guardarContacto'),null);}finally{b.w.close();}});
test('Etapa4 UI: respuesta tardía no reemplaza otro panel',async()=>{let done;const b=browser(()=>new Promise(r=>done=r));try{const pending=b.w.abrirContactosCobranza('c','qa');b.w.openSheet('<p>Otro panel</p>');done(ficha);await pending;assert.equal(b.el('activeSheet').textContent,'Otro panel');}finally{b.w.close();}});
test('Etapa4 UI: cambiar negocio invalida el envío y no altera otro cliente',async()=>{const b=browser();try{await b.w.abrirContactosCobranza('c','qa');b.w.qaState.negocioActual='otro';b.el('guardarContacto').click();await tick();assert.equal(b.calls.filter(c=>c.opts.method).length,0);}finally{b.w.close();}});
test('Etapa4 UI: historial conserva fechas anteriores y neutraliza HTML',()=>{const b=browser();try{const html=b.w.historialContactosHtml({contactosCobranza:[{negocio_id:'qa',numero:1,estado:'pendiente',fecha_contacto:'2026-10-12',fecha_vencimiento_real:'2026-10-01',nota:'<img src=x onerror=alert(1)>',historial:[{accion:'reprogramar',fecha_hora:'2026-10-08',autor:'QA',motivo:'Acuerdo',datos_anteriores:JSON.stringify({fecha_contacto:'2026-10-10'}),datos_nuevos:JSON.stringify({fecha_contacto:'2026-10-12'})}]}]},'qa');assert.match(html,/10\/10\/2026/);assert.match(html,/12\/10\/2026/);assert.ok(!html.includes('<img'));}finally{b.w.close();}});
test('Etapa4 UI: reprogramación parte de la fecha guardada y realizar contacto no pide otra fecha',async()=>{const b=browser(()=>({...ficha,contactosCobranza:[{id:'r1',negocio_id:'qa',cuota_id:'q1',numero:1,fecha_contacto:'2026-11-12',estado:'pendiente',reprogramado_fecha:null,nota:'QA'}]}));try{await b.w.abrirContactosCobranza('c','qa');assert.equal(b.el('contactoFecha').value,'2026-11-12');b.el('contactoAccion').value='realizado';b.el('contactoAccion').dispatchEvent(new b.w.Event('change'));assert.equal(b.el('contactoFecha').closest('.field').hidden,true);}finally{b.w.close();}});
